version: '3.8'

services:
  # MySQL service
  mysql:
    build: 
      context: ./backend
      dockerfile: Dockerfile.mysql
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "--password=${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}

  # Frontend service
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: react_app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  mysql_data: 