FROM mysql:8.0

# Change later
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=onlybids_database
ENV MYSQL_USER=mysql_user
ENV MYSQL_PASSWORD=mysql_user_password

# https://hub.docker.com/_/mysql
COPY init.sql /docker-entrypoint-initdb.d/01-init.sql
COPY seed.sql /docker-entrypoint-initdb.d/02-seed.sql
COPY event.sql /docker-entrypoint-initdb.d/03-event.sql

# Set permissions
RUN chmod 644 /docker-entrypoint-initdb.d/*.sql 