version: '3.8'

services:
  # MySQL service
  mysql:
    build: .
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: onlybids_database
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_user_password
    volumes:
      - mysql_data:/var/lib/mysql

  # Node.js service
  app:
    build: 
      context: .
      dockerfile: Dockerfile.node
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql_db
      - DB_USER=mysql_user
      - DB_PASSWORD=mysql_user_password
      - DB_NAME=onlybids_database
      - PORT=3000

volumes:
  mysql_data: 